#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#- Nginx should be listening on port 80
#- When querying Nginx at its root / with a GET request (requesting a page)\
#- using curl, it must return a page that contains the string Hello World!
#- As an answer file, write a Bash script that configures a new Ubuntu machine\
#- to respect above requirements (this script will be run on the server itself)
#- You can’t use systemctl for restarting nginx

ADD301_REDIRECT="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default
sudo service nginx restart

