#!/usr/bin/env bash
# Running and listening NGNIX on port 80 of all server's active IPv4 IPs

mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
service nginx stop
pkill nginx
service nginx start
