#!/usr/bin/env bash
# Running and listening NGNIX on port 80 of all server's active IPv4 IPs

rm /etc/nginx/sites-available/*
rm /etc/nginx/sites-enabled/*~
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart

