#!/usr/bin/env bash
# Tell the story of passwd

file="/etc/passwd"

while IFS= read -r line; do
  user_name=$(echo "$line" | cut -d ':' -f1)
  gid=$(echo "$line" | cut -d ':' -f4)
  hdir=$(echo "$line" | cut -d ':' -f6)
  shell=$(echo "$line" | cut -d ':' -f7)
  uid=$(echo "$line" | cut -d ':' -f3)
  password=$(echo "$line" | cut -d ':' -f2)
  idinf=$(echo "$line" | cut -d ':' -f5)

  echo "The user $user_name is part of the $gid gang, lives in $hdir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $idinf"
done < "$file"
